services:
  postgres:
    image: postgres
    restart: always
    container_name: library_db
    ports:
      - '5434:5432'
    expose:
      - 5432
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U library -d library_db']
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    container_name: log_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: log_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data: